name: Release

on:
  push:
    tags: [ "v*" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
      - run: npm ci
      - run: |
          mkdir -p ./slide
          cp -R ./assets ./slide/
          npm run export -- -o slide/index.html slide.md
          tar czf slide.tar.gz slide
      - uses: actions/upload-artifact@v4
        with:
          name: slide-archive
          path: ./slide.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.result == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: actions/download-artifact@v4
        with:
          name: slide-archive
      - run: |
          gh release create -d -n '' -t "$TAG_NAME" "$TAG_NAME" slide.tar.gz
        env:
          TAG_NAME: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}
